"""Initial SQLAlchemy migration

Revision ID: 1eef0d726ee0
Revises: 
Create Date: 2026-05-29 01:13:29.015893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eef0d726ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('session_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_scans_barcode'))
        batch_op.drop_index(batch_op.f('idx_scans_session_name'))
        batch_op.drop_index(batch_op.f('idx_scans_timestamp'))
        batch_op.create_index(batch_op.f('ix_scans_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_session_name'), ['session_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scans_session_name'))
        batch_op.drop_index(batch_op.f('ix_scans_barcode'))
        batch_op.create_index(batch_op.f('idx_scans_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_scans_session_name'), ['session_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_scans_barcode'), ['barcode'], unique=False)
        batch_op.alter_column('session_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('barcode',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('role', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('session_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('last_active',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_active',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('session_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###

