"""add composite covering indexes

Revision ID: d412e991ebbf
Revises: 1eef0d726ee0
Create Date: 2026-05-29 01:21:57.218075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd412e991ebbf'
down_revision = '1eef0d726ee0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('idx_scans_composite_lookup', ['barcode', 'user', 'branch', 'session_name'], unique=False)
        batch_op.create_index('idx_scans_covering_admin', ['barcode', 'user', 'branch', 'session_name', 'is_damaged', 'is_flagged', 'timestamp'], unique=False)
        batch_op.create_index('idx_scans_covering_summary', ['user', 'session_name', 'barcode', 'is_damaged', 'is_flagged', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('idx_scans_covering_summary')
        batch_op.drop_index('idx_scans_covering_admin')
        batch_op.drop_index('idx_scans_composite_lookup')

    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

